# Generated by Django 2.1.7 on 2019-03-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190321_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='account_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='account_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
