# Generated by Django 2.2 on 2019-04-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20190322_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountDetail',
        ),
    ]
