# Generated by Django 2.2 on 2019-04-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_delete_accountdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
