# Generated by Django 2.2 on 2019-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20190426_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Applications', 'Applications'), ('Network & Security', 'Network & Security'), ('Solutions', 'Solutions'), ('Sales', 'Sales'), ('Finance', 'Finance'), ('Projects', 'Projects'), ('Research & Development', 'Research & Development')], max_length=100),
        ),
    ]
