# Generated by Django 2.1.7 on 2019-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_auto_20190304_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='Year',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=100),
        ),
    ]
