# Generated by Django 2.1.7 on 2019-03-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20190304_1308'),
        ('payroll_app', '0005_auto_20190304_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grant_payroll', models.BooleanField()),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.Salary')),
            ],
        ),
    ]
