# Generated by Django 2.1.7 on 2019-03-05 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0006_salarypayroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayroll',
            name='grant_payroll',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='salarypayroll',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payrolls', to='salary.Salary'),
        ),
    ]
