# Generated by Django 2.1.7 on 2019-03-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_auto_20190305_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarypayroll',
            old_name='grant_payroll',
            new_name='status',
        ),
    ]
