# Generated by Django 2.1.7 on 2019-03-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_auto_20190305_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarypayroll',
            old_name='grant_payroll',
            new_name='status',
        ),
        migrations.AddField(
            model_name='salarypayroll',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payrolls', to='payroll_app.Month'),
            preserve_default=False,
        ),
    ]
