# Generated by Django 2.1.7 on 2019-03-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0008_auto_20190305_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayroll',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payrolls', to='payroll_app.Year'),
            preserve_default=False,
        ),
    ]
