# Generated by Django 2.1.5 on 2019-02-03 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('total_working_days', models.IntegerField()),
                ('travel_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('leave_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('performance_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('transport_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('medical_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('tax_deduction', models.IntegerField(blank=True, default=0, null=True)),
                ('other_deductions', models.IntegerField(blank=True, default=0, null=True)),
                ('month_pay', models.CharField(max_length=100)),
                ('year_salary', models.CharField(max_length=100)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'salaries',
            },
        ),
    ]
